[package]
name = "teensy3"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>", "James Munns <james.munns@gmail.com"]
build = "build.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
