[package]
name = "teensy3"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>", "James Munns <james.munns@gmail.com>"]
license = "MIT"
description = "Rust interface layer for the Teensy 3.1/3.2 microcontroller"
repository = "https://github.com/jamesmunns/teensy3-rs"

[dependencies]
teensy3-sys = "0.1"
